// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_doc_chat from "./routes/api/doc-chat.ts";
import * as $api_doc_summary from "./routes/api/doc-summary.ts";
import * as $api_research_network from "./routes/api/research-network.ts";
import * as $api_search from "./routes/api/search.ts";
import * as $api_supabase from "./routes/api/supabase.ts";
import * as $api_types from "./routes/api/types.ts";
import * as $doc_chat_filename_ from "./routes/doc-chat/[filename].tsx";
import * as $download from "./routes/download.ts";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $AtmosphericOverlay from "./islands/AtmosphericOverlay.tsx";
import * as $DepthGauge from "./islands/DepthGauge.tsx";
import * as $DocChat from "./islands/DocChat.tsx";
import * as $FishTank from "./islands/FishTank.tsx";
import * as $Game404 from "./islands/Game404.tsx";
import * as $MarineAtmosphere from "./islands/MarineAtmosphere.tsx";
import * as $MarinePulse from "./islands/MarinePulse.tsx";
import * as $NavigationWithSearch from "./islands/NavigationWithSearch.tsx";
import * as $NeuralFish from "./islands/NeuralFish.tsx";
import * as $OceanicHUD from "./islands/OceanicHUD.tsx";
import * as $PaperCardContent from "./islands/PaperCardContent.tsx";
import * as $PdfViewer from "./islands/PdfViewer.tsx";
import * as $ResearchNetwork from "./islands/ResearchNetwork.tsx";
import * as $ScrollController from "./islands/ScrollController.tsx";
import * as $SkillsCompass from "./islands/SkillsCompass.tsx";
import * as $SpectraTrace from "./islands/SpectraTrace.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/doc-chat.ts": $api_doc_chat,
    "./routes/api/doc-summary.ts": $api_doc_summary,
    "./routes/api/research-network.ts": $api_research_network,
    "./routes/api/search.ts": $api_search,
    "./routes/api/supabase.ts": $api_supabase,
    "./routes/api/types.ts": $api_types,
    "./routes/doc-chat/[filename].tsx": $doc_chat_filename_,
    "./routes/download.ts": $download,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/AtmosphericOverlay.tsx": $AtmosphericOverlay,
    "./islands/DepthGauge.tsx": $DepthGauge,
    "./islands/DocChat.tsx": $DocChat,
    "./islands/FishTank.tsx": $FishTank,
    "./islands/Game404.tsx": $Game404,
    "./islands/MarineAtmosphere.tsx": $MarineAtmosphere,
    "./islands/MarinePulse.tsx": $MarinePulse,
    "./islands/NavigationWithSearch.tsx": $NavigationWithSearch,
    "./islands/NeuralFish.tsx": $NeuralFish,
    "./islands/OceanicHUD.tsx": $OceanicHUD,
    "./islands/PaperCardContent.tsx": $PaperCardContent,
    "./islands/PdfViewer.tsx": $PdfViewer,
    "./islands/ResearchNetwork.tsx": $ResearchNetwork,
    "./islands/ScrollController.tsx": $ScrollController,
    "./islands/SkillsCompass.tsx": $SkillsCompass,
    "./islands/SpectraTrace.tsx": $SpectraTrace,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
