name: Deploy
on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Deploy to Deno Deploy
        run: deno deploy --token=${{ secrets.DENO_DEPLOY_TOKEN }} --project=woodrock --entrypoint=main.ts

